name: ci

on: [push]

env:
  SERVER_PATH: server/src/
  WEB_PATH: web/

jobs:
  Server-Compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Arduino CLI
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          libraries: |
            - name: Ethernet
            - name: SD
          sketch-paths: |
            - ${{ env.SERVER_PATH }}

  Server-Format-Check:
    needs: [Server-Compile]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Setup Clang Formatter
        uses: actions/checkout@v5
        with:
          repository: adafruit/ci-arduino
          path: ci

      - name: Check correct code formatting with clang-format
        run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" --extensions "ino" -r ${{ env.SERVER_PATH }}

  Web-Format-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.x

      - name: Install dependecies
        working-directory: ${{ env.WEB_PATH }}
        run: npm ci

      - name: Check format
        working-directory: ${{ env.WEB_PATH }}
        run: npm run format:check

  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Docker build
        run: docker build -t remote-switch .

      - name: Run container
        run: |
          docker run --rm -d \
          -p 80:80 \
          --name remote-switch remote-switch

      - name: Wait for container to start
        run: sleep 5

      - name: Ping
        run: |
          if curl -f http://localhost:80 | grep -q "<title>PC Switch</title>"; then
              echo "Title found!"
          else
              echo "Error: '<title>PC Switch</title>' not found." >&2
              exit 1
          fi

      - name: Stop container
        run: docker stop remote-switch