name: Release

on:
  release:
    types: [released, prereleased]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v6
        if: ${{ !github.event.release.prerelease }}
        with:
          context: ./web
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/matiasg19/arduino-remote-switch:latest
            ghcr.io/matiasg19/arduino-remote-switch:${{ github.ref_name }}
          build-args: |
            TAG=${{ github.ref_name }}

      - name: Build and push Docker image (prerelease)
        uses: docker/build-push-action@v6
        if: ${{ github.event.release.prerelease }}
        with:
          context: ./web
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/matiasg19/arduino-remote-switch:pre
            ghcr.io/matiasg19/arduino-remote-switch:${{ github.ref_name }}
          build-args: |
            TAG=${{ github.ref_name }}